BASE <http://example.org/>
PREFIX dash: <http://datashapes.org/dash#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX cube: <https://cube.link/> 

# For each cube:Cube create a link between the shape and
# all linked observations. This will validate each observation
# linked in observationSet

CONSTRUCT {
?shapeIri a sh:NodeShape ;
  schema:dataset ?cube ;
  sh:targetNode ?observationSet ;
  sh:property [
    sh:node ?observationShape ;
    sh:path cube:observation;
  ].

} WHERE {
  ?cube a cube:Cube ;
    cube:observationSet ?observationSet ;
    cube:observationConstraint ?observationShape ;

    # As this is just used for validation, UUID should be enough
    BIND( UUID() AS ?shapeIri)
}