PREFIX dash: <http://datashapes.org/dash#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX cube: <https://cube.link/> 


# Check if we have any IRIs referenced in sh:in lists in a shape
# that do not exist.
SELECT DISTINCT ?member WHERE {

  ?cube a cube:Cube ;
    cube:observationConstraint ?observationShape .
  
  ?observationShape a sh:NodeShape ;
    sh:property/sh:in ?list .

    ?list rdf:rest*/rdf:first  ?member .

    MINUS {
        ?member ?p ?o
    }

    FILTER (isIRI(?member))

}